# Generated by Django 4.2.7 on 2024-01-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aisapp', '0002_alter_info_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField()),
                ('concern', models.CharField(max_length=50)),
                ('query', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=50)),
            ],
        ),
    ]
